### ISSUE TITLE
Index.html page for new Web Club Website

### ISSUE THREAD

**Issue by sbshah97** [WebClub-NITK/old_website#16]
* Kindly take a look at [this link](https://github.com/WebClub-NITK/WebClub-NITK.github.io/wiki/Index) for further information.

**Comment by Hrily** [comment]
![image](https://user-images.githubusercontent.com/13836720/34480409-4695c634-efd2-11e7-9649-988e4b8becb1.png)
![image](https://user-images.githubusercontent.com/13836720/34480414-4b4edf62-efd2-11e7-97ad-aaa007343962.png)
![image](https://user-images.githubusercontent.com/13836720/34480416-50a2fa84-efd2-11e7-94f3-5f639e622f35.png)

You'll need to have good transitions between these. PM me for details.
