### ISSUE TITLE
Events page for Web Club Website

### ISSUE THREAD

**Issue by sbshah97** [WebClub-NITK/old_website#17]
* Kindly take a look at [this link](https://github.com/WebClub-NITK/WebClub-NITK.github.io/wiki/Events) for further information.

**Comment by Hrily** [comment]
![image](https://user-images.githubusercontent.com/13836720/34550567-0d048038-f138-11e7-9d17-05c4df368e3f.png)

**Comment by sbshah97** [comment]
Looks good !
