### ISSUE TITLE
Projects Page for Web Club Website

### ISSUE THREAD

**Issue by sbshah97** [WebClub-NITK/old_website#18]
* Kindly take a look at [this link](https://github.com/WebClub-NITK/WebClub-NITK.github.io/wiki/Projects) for further information.

**Comment by Hrily** [comment]
![image](https://user-images.githubusercontent.com/13836720/34550917-d98a8632-f13a-11e7-9eb5-95ce2c36d4f5.png)
![image](https://user-images.githubusercontent.com/13836720/34550919-ded7f5f2-f13a-11e7-8a24-3d63a48a8361.png)

**Comment by Hrily** [comment]
@salman-bhai 

> Give description regarding the types of project that are undertaken.

Do we have content for this?

**Comment by sbshah97** [comment]
Yes, we will! Currently I need to get it from ongoing projects that are happening in Web Club this semester
