### ISSUE TITLE
Team Page for Web Club Website

### ISSUE THREAD

**Issue by sbshah97** [WebClub-NITK/old_website#19]
* Kindly take a look at [this link](https://github.com/WebClub-NITK/WebClub-NITK.github.io/wiki/Team) for further information.

**Comment by Hrily** [comment]
![image](https://user-images.githubusercontent.com/13836720/34673884-d0915926-f4a9-11e7-9924-3b8afac0a170.png)
![image](https://user-images.githubusercontent.com/13836720/34673887-d3eb3024-f4a9-11e7-82e0-3d1ce518b813.png)
You can put the social icons right aligned here
