### ISSUE TITLE
Programming Contests Page for Web Club Website

### ISSUE THREAD

**Issue by sbshah97** [WebClub-NITK/old_website#20]
* Kindly take a look at [this link](https://github.com/WebClub-NITK/WebClub-NITK.github.io/wiki/Contests) for further information.

**Comment by Hrily** [comment]
![image](https://user-images.githubusercontent.com/13836720/34612347-635f5b2a-f24f-11e7-883a-1cbdd83a9573.png)
Put "Programming Contest" instead of "Events"...
