### ISSUE TITLE
Add data to contests.json file based on previous Programming Contests

### ISSUE THREAD

**Issue by sbshah97** [WebClub-NITK/old_website#21]
Please take a look at [this link](https://github.com/WebClub-NITK/WebClub-NITK.github.io/wiki/contests.json) for further information

**Comment by sbshah97** [comment]
Any progress @vilas897

**Comment by sbshah97** [comment]
@vilas897 please finish it off!

**Comment by sbshah97** [comment]
@vilas897 any updates?

**Comment by SaurabhAgarwala** [comment]
Closing as this will become irrelevant with the onset of the new website.
