### ISSUE TITLE
Add Header/Footer/Menu to link to other pages in the website

### ISSUE THREAD

**Issue by sbshah97** [WebClub-NITK/old_website#30]
* Need to add header/footer to link to other pages in the website. Header should fit over the current design and work on it!

Please either do it yourself if it isn't a big deal or assign someone this work!

**Comment by Hrily** [comment]
I think header wont look good with current theme.
We can have a header at left edge of the screen (like the one you can see in my blog), what do you say???

**Comment by Hrily** [comment]
[web-club.pdf](https://github.com/WebClub-NITK/WebClub-NITK.github.io/files/1621582/web-club.pdf)
Refer this pdf for header, footer and menu.

I'll add the menu and close icons in a while.

**Comment by Hrily** [comment]
I've added the icons...

**Comment by sbshah97** [comment]
looks good @Hrily
