### ISSUE TITLE
Add data to team.json file and images for post bearers.

### ISSUE THREAD

**Issue by pvgupta24** [WebClub-NITK/old_website#39]
- [ ] Get club members info [here](https://drive.google.com/open?id=1VUwb1rycg2L5a0ge68JbApR_1dV4Ios0) and convert it into JSON using the google sheets add-on.
- [ ] All the profile links of members to be updated.
- [ ] Post bearer's images to be added in images/posts/ directory and the same to be updated in team.json.

**Comment by salman-bhai** [comment]
Create a new Google sheet for people! Where people can add links to which image they want to put up as well as other details

**Comment by SaurabhAgarwala** [comment]
Closing as this will become irrelevant with the onset of the new website.
