### ISSUE TITLE
Add Header in Events and Contests

### ISSUE THREAD

**Issue by sbshah97** [WebClub-NITK/old_website#41]
* This [particular page](http://webclub-nitk.github.io/events) doesn't have any header. Please add some over there!

*  This [particular page](http://webclub-nitk.github.io/contests) doesn't have any header. Please add some over there!

![screen shot 2018-01-19 at 12 51 46](https://user-images.githubusercontent.com/16410361/35139095-9bdaab94-fd17-11e7-9d1c-8f86b07a2be9.png)

Footer is not optimised for mobile

![screen shot 2018-01-19 at 12 52 55](https://user-images.githubusercontent.com/16410361/35139126-bcc112b2-fd17-11e7-9a34-624614a2975a.png)

Again same Issue for team page

**Comment by sbshah97** [comment]
@suhasbs any updates on this?

**Comment by SaurabhAgarwala** [comment]
Closing as this will become irrelevant with the onset of the new website.
