### ISSUE TITLE
Sidebar fixes

### ISSUE THREAD

**Issue by pvgupta24** [WebClub-NITK/old_website#45]
- [ ] Issues in the navbar while displaying the menu open/close buttons. 
- [ ] Move the sidenav to the left end.
![screenshot from 2018-09-29 16-19-04](https://user-images.githubusercontent.com/21684823/46244909-91829400-c403-11e8-9667-d005c343dc4c.png)
![screenshot from 2018-09-29 16-25-49](https://user-images.githubusercontent.com/21684823/46244967-79f7db00-c404-11e8-9718-cced6704d261.png)

**Comment by SaurabhAgarwala** [comment]
Closing as this will become irrelevant with the onset of the new website.
