### ISSUE TITLE
Make Events section intelligent and other enhancements

### ISSUE THREAD

**Issue by Hrily** [WebClub-NITK/old_website#48]
The events section in homepage shows upcoming events. But not always we have upcoming events. This makes the events sections empty.

A smarter way would be to show top three events, regardless of their status (upcoming/previous).
And also mark the upcoming events with `Upcoming` tag.
This applies to events page as well.

Also, the granularity of period in the events page is months which is too less. Semester will be better.

Following prototypes will give you an idea.

![web-club-events](https://user-images.githubusercontent.com/13836720/46276968-54431100-c57f-11e8-9bf6-288ecf59838f.jpg)
![web-club-events-full](https://user-images.githubusercontent.com/13836720/46277055-9ff5ba80-c57f-11e8-9e7f-03fc995465f5.jpg)

So the following tasks are to be done for this issue:

+ Make events listing smarter for events section in home page
+ Mark upcoming events with `Upcoming` tag
+ Change period of events listing to semester

**Comment by SaurabhAgarwala** [comment]
Closing as this will become irrelevant with the onset of the new website.
