### ISSUE TITLE
Change Web Club title to Web Enthusiasts' Club and Add Logo

### ISSUE THREAD

**Issue by Hrily** [WebClub-NITK/old_website#49]
+ Change every occurrence of Web Club to Web Enthusiasts Club
+ Add Logo to home page. Logo can be found [here](https://drive.google.com/file/d/17ra05NCXAGXJC34bQzrYPIXIldectGJX/view?usp=sharing)

Following prototype will give idea
![web-club-home-about](https://user-images.githubusercontent.com/13836720/46277636-51e1b680-c581-11e8-81d2-b87a411a4e8b.jpg)

**Comment by sbshah97** [comment]
@Hrily is it `NITK Web Enthusiasts Club` or is it `Web Enthusiasts Club`?

**Comment by Hrily** [comment]
I think `Web Enthusiasts' Club NITK`

@vilas897 can tell the exact

**Comment by vilas897** [comment]
Yea @Hrily is right. It's "Web Enthusiasts' Club, NITK"
