### ISSUE TITLE
Add Groups Section to Homepage

### ISSUE THREAD

**Issue by Hrily** [WebClub-NITK/old_website#50]
+ Remove Highlights section from Homepage (the section after events, before footer)
+ Add Groups Section. See below for desktop and mobile prototypes.
+ Interchange Groups and Events sections. Second should be Groups and third should be Events.

_Note:_ This issue will be `on hold` until all the groups post the content to be written as their group description.

Prototypes for Groups section
![web-club-groups](https://user-images.githubusercontent.com/13836720/46278336-7a6ab000-c583-11e8-8f9d-d44371368ba0.jpg)
![web-club-groups-mob](https://user-images.githubusercontent.com/13836720/46278291-5ad38780-c583-11e8-8b16-f92fd4dfc5b5.jpg)

**Comment by SaurabhAgarwala** [comment]
Closing as this will become irrelevant with the onset of the new website.
