### ISSUE TITLE
Update the content on home page. 

### ISSUE THREAD

**Issue by viggi-v** [WebClub-NITK/old_website#51]
The about us (first section) says this:
>Hello, World
>We are group of motivated, passionate students who provide help, technical support, education(in form of talks, lectures, workshops, demonstrations, code showcases, etc.) to each other as well as to anyone else who is interested; other students, faculty and any denizen of National Institute of Technology Karanataka, Surathkal

This can be changed, with punctuations as well as adding a link to nitk.ac.in where the institute name is mentioned. 
Also, the mouse pointer while hovering over `nav.header` is a cursor now, it can be changed using `cursor: default;` for all the titles.

**Comment by SaurabhAgarwala** [comment]
Closing as this will become irrelevant with the onset of the new website.
