### ISSUE TITLE
Link the slides of Lecture Repo to Main Repo

### ISSUE THREAD

**Issue by sigsevneo** [WebClub-NITK/old_website#6]
Shift the slides (such as those added in https://github.com/WebClub-NITK/WebClub-NITK.github.io/commit/a163647ba2b9c4c2b1e8973da26a21c68df61d3e) to the [lecture repo](https://github.com/WebClub-NITK/Lecture-Repo).

**Comment by ujdcodr** [comment]
do i mark it as resolved before or after merging??

**Comment by sigsevneo** [comment]
After merging.

**Comment by ujdcodr** [comment]
issue resolved by PR #7 and #8

**Comment by adeepkit01** [comment]
![screenshot from 2016-11-28 13-55-00](https://cloud.githubusercontent.com/assets/7664386/20660987/50a6af3a-b572-11e6-9ad3-394ed3b8ec0d.png)
All the links are broken @sigsevneo @ujdcodr

**Comment by adeepkit01** [comment]
Ok broken links are fixed but it goes into the repository page, I guess the whole enhancement just backfired

**Comment by sigsevneo** [comment]
The links [here](https://github.com/WebClub-NITK/WebClub-NITK.github.io/blob/master/blogs.html#L37) and [here](https://github.com/WebClub-NITK/WebClub-NITK.github.io/blob/master/blogs.html#L31) seem broken. @ujdcodr Please rectify it.

**Comment by sigsevneo** [comment]
@adeepkit01 @ujdcodr 
Change the "blob" to "raw". Should fix the redirect to that page.

**Comment by adeepkit01** [comment]
raw will lead to auto download

**Comment by sigsevneo** [comment]
Seems cleaner? Linking the material from the repo this way, the user can read it how they desire.

**Comment by ujdcodr** [comment]
yeah i'll look into it

**Comment by ujdcodr** [comment]
so should i go with 'raw' or leave it??

**Comment by ujdcodr** [comment]
where is the git cheet sheet?

**Comment by ujdcodr** [comment]
solved by PR #9

**Comment by adeepkit01** [comment]
https://education.github.com/git-cheat-sheet-education.pdf use this

**Comment by ujdcodr** [comment]
same stuff

**Comment by ujdcodr** [comment]
i used https://services.github.com/on-demand/downloads/github-git-cheat-sheet.pdf

**Comment by ujdcodr** [comment]
well almost...

**Comment by ujdcodr** [comment]
done

**Comment by ujdcodr** [comment]
apparently there is a workaround for the problem
http://webapps.stackexchange.com/questions/48061/can-i-trick-github-into-displaying-the-pdf-in-the-browser-instead-of-downloading

**Comment by adeepkit01** [comment]
you can use google docs viewer

**Comment by ujdcodr** [comment]
Wow...i just did that before seeing your comment ^_^

**Comment by ujdcodr** [comment]
well then...merge and check

**Comment by adeepkit01** [comment]
@ujdcodr you have been added as a collab for this repo, also I have enabled mandatory reviews. I am closing this

**Comment by ujdcodr** [comment]
Sure thing bruh... what are mandatory reviews?
